//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoxTools.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoxTools.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die activate ähnelt.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always show Versionselectiondialog ähnelt.
        /// </summary>
        internal static string AlwaysShowVersionDialog {
            get {
                return ResourceManager.GetString("AlwaysShowVersionDialog", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        internal static string ApplicationVersionFormat {
            get {
                return ResourceManager.GetString("ApplicationVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close all open Configs ähnelt.
        /// </summary>
        internal static string CloseAllConfigs {
            get {
                return ResourceManager.GetString("CloseAllConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Application ähnelt.
        /// </summary>
        internal static string CloseApplications {
            get {
                return ResourceManager.GetString("CloseApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config directory paths ähnelt.
        /// </summary>
        internal static string ConfigDirectoryPaths {
            get {
                return ResourceManager.GetString("ConfigDirectoryPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deactivate ähnelt.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected as default ähnelt.
        /// </summary>
        internal static string DefaultSelected_Label {
            get {
                return ResourceManager.GetString("DefaultSelected_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Version ähnelt.
        /// </summary>
        internal static string defaultVersion {
            get {
                return ResourceManager.GetString("defaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This version is used by default when opening files via the tool. ähnelt.
        /// </summary>
        internal static string DefaultVersion_FootnoteText {
            get {
                return ResourceManager.GetString("DefaultVersion_FootnoteText", resourceCulture);
            }
        }

        internal static string DefaultConfigPathLabel {
            get {
                return ResourceManager.GetString("DefaultConfigPathLabel", resourceCulture);
            }
        }

        internal static string DefaultProjectPathLabel {
            get {
                return ResourceManager.GetString("DefaultProjectPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * ähnelt.
        /// </summary>
        internal static string Footnote_Asterisk {
            get {
                return ResourceManager.GetString("Footnote_Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installationpaths ähnelt.
        /// </summary>
        internal static string Installationpaths {
            get {
                return ResourceManager.GetString("Installationpaths", resourceCulture);
            }
        }

        internal static string InitialSetup_DefaultPathMissing {
            get {
                return ResourceManager.GetString("InitialSetup_DefaultPathMissing", resourceCulture);
            }
        }

        internal static string InitialSetup_ReadRegisteredAppsFailed {
            get {
                return ResourceManager.GetString("InitialSetup_ReadRegisteredAppsFailed", resourceCulture);
            }
        }

        internal static string InitialSetup_RegisterCapabilitiesFailed {
            get {
                return ResourceManager.GetString("InitialSetup_RegisterCapabilitiesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoInstallationPath_Title ähnelt.
        /// </summary>
        internal static string NoInstallationPath_Title {
            get {
                return ResourceManager.GetString("NoInstallationPath_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoInstallationPath_Description ähnelt.
        /// </summary>
        internal static string NoInstallationPath_Description {
            get {
                return ResourceManager.GetString("NoInstallationPath_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use suggested path ähnelt.
        /// </summary>
        internal static string NoInstallationPath_UseSuggestedButton {
            get {
                return ResourceManager.GetString("NoInstallationPath_UseSuggestedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed Versions ähnelt.
        /// </summary>
        internal static string InstalledVersions {
            get {
                return ResourceManager.GetString("InstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No installed Config Versions were found! ähnelt.
        /// </summary>
        internal static string NoInstalledConfigVersionsFound {
            get {
                return ResourceManager.GetString("NoInstalledConfigVersionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Loxone App ähnelt.
        /// </summary>
        internal static string OpenLxApp {
            get {
                return ResourceManager.GetString("OpenLxApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path already exists ähnelt.
        /// </summary>
        internal static string PathAlreadyExists {
            get {
                return ResourceManager.GetString("PathAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pressing Middle Mousebutton ähnelt.
        /// </summary>
        internal static string PressingMiddleMouseButton {
            get {
                return ResourceManager.GetString("PressingMiddleMouseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Directorypaths ähnelt.
        /// </summary>
        internal static string ProjectDirectorypaths {
            get {
                return ResourceManager.GetString("ProjectDirectorypaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Folder ähnelt.
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoProjectPath_Title ähnelt.
        /// </summary>
        internal static string NoProjectPath_Title {
            get {
                return ResourceManager.GetString("NoProjectPath_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoProjectPath_Description ähnelt.
        /// </summary>
        internal static string NoProjectPath_Description {
            get {
                return ResourceManager.GetString("NoProjectPath_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use suggested path ähnelt.
        /// </summary>
        internal static string NoProjectPath_UseSuggestedButton {
            get {
                return ResourceManager.GetString("NoProjectPath_UseSuggestedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run Application at Windows Startup ähnelt.
        /// </summary>
        internal static string RunAtWindowsStartup {
            get {
                return ResourceManager.GetString("RunAtWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select as default ähnelt.
        /// </summary>
        internal static string SelectAsDefault_Button {
            get {
                return ResourceManager.GetString("SelectAsDefault_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as default Version ähnelt.
        /// </summary>
        internal static string SetAsDefaultVersion {
            get {
                return ResourceManager.GetString("SetAsDefaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string ShortcutDescription {
            get {
                return ResourceManager.GetString("ShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always show dialog on start ähnelt.
        /// </summary>
        internal static string SettingsAlwaysShowDialogHint {
            get {
                return ResourceManager.GetString("SettingsAlwaysShowDialogHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folders where projects are stored ähnelt.
        /// </summary>
        internal static string SettingsProjectFoldersHint {
            get {
                return ResourceManager.GetString("SettingsProjectFoldersHint", resourceCulture);
            }
        }

        internal static string SettingsUpdateChannelTitle {
            get {
                return ResourceManager.GetString("SettingsUpdateChannelTitle", resourceCulture);
            }
        }

        internal static string SettingsUpdateChannelHint {
            get {
                return ResourceManager.GetString("SettingsUpdateChannelHint", resourceCulture);
            }
        }

        internal static string SettingsUpdateChannel_Release {
            get {
                return ResourceManager.GetString("SettingsUpdateChannel_Release", resourceCulture);
            }
        }

        internal static string SettingsUpdateChannel_Beta {
            get {
                return ResourceManager.GetString("SettingsUpdateChannel_Beta", resourceCulture);
            }
        }

        internal static string SettingsUpdateChannel_Alpha {
            get {
                return ResourceManager.GetString("SettingsUpdateChannel_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        internal static string SettingsSectionAdvanced {
            get {
                return ResourceManager.GetString("SettingsSectionAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string SettingsSectionGeneral {
            get {
                return ResourceManager.GetString("SettingsSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paths ähnelt.
        /// </summary>
        internal static string SettingsSectionPaths {
            get {
                return ResourceManager.GetString("SettingsSectionPaths", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File association „hnelt.
        /// </summary>
        internal static string Settings_FileAssociation_Title {
            get {
                return ResourceManager.GetString("Settings_FileAssociation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default app is managed by Windows. Click below to change it. „hnelt.
        /// </summary>
        internal static string Settings_FileAssociation_Description {
            get {
                return ResourceManager.GetString("Settings_FileAssociation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current: „hnelt.
        /// </summary>
        internal static string Settings_FileAssociation_Current {
            get {
                return ResourceManager.GetString("Settings_FileAssociation_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mixed „hnelt.
        /// </summary>
        internal static string Settings_FileAssociation_Mixed {
            get {
                return ResourceManager.GetString("Settings_FileAssociation_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not set „hnelt.
        /// </summary>
        internal static string Settings_FileAssociation_NotSet {
            get {
                return ResourceManager.GetString("Settings_FileAssociation_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Windows default apps. „hnelt.
        /// </summary>
        internal static string Settings_FileAssociation_OpenWindowsButton {
            get {
                return ResourceManager.GetString("Settings_FileAssociation_OpenWindowsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t start LoxoneConfig!\nError: {0} ähnelt.
        /// </summary>
        internal static string StartConfigFailed {
            get {
                return ResourceManager.GetString("StartConfigFailed", resourceCulture);
            }
        }

        internal static string LaunchModeTitle {
            get {
                return ResourceManager.GetString("LaunchModeTitle", resourceCulture);
            }
        }

        internal static string LaunchModeHint {
            get {
                return ResourceManager.GetString("LaunchModeHint", resourceCulture);
            }
        }

        internal static string LaunchModeManagedHint {
            get {
                return ResourceManager.GetString("LaunchModeManagedHint", resourceCulture);
            }
        }

        internal static string FixedVersionSelectLabel {
            get {
                return ResourceManager.GetString("FixedVersionSelectLabel", resourceCulture);
            }
        }

        internal static string OpenSettingsLabel {
            get {
                return ResourceManager.GetString("OpenSettingsLabel", resourceCulture);
            }
        }

        internal static string LatestInstalledVersionLabel {
            get {
                return ResourceManager.GetString("LatestInstalledVersionLabel", resourceCulture);
            }
        }

        internal static string UseLatestVersionOptionTitle {
            get {
                return ResourceManager.GetString("UseLatestVersionOptionTitle", resourceCulture);
            }
        }

        internal static string UseLatestVersionOptionHint {
            get {
                return ResourceManager.GetString("UseLatestVersionOptionHint", resourceCulture);
            }
        }

        internal static string UseFixedVersionOptionTitle {
            get {
                return ResourceManager.GetString("UseFixedVersionOptionTitle", resourceCulture);
            }
        }

        internal static string UseFixedVersionOptionHint {
            get {
                return ResourceManager.GetString("UseFixedVersionOptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run when starting Windows ähnelt.
        /// </summary>
        internal static string String1RunAtWindowsStartup {
            get {
                return ResourceManager.GetString("String1RunAtWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Middle-click the tray icon to close all running Loxone Config instances. ähnelt.
        /// </summary>
        internal static string TerminateAllLoxoneConfigInstances_Description {
            get {
                return ResourceManager.GetString("TerminateAllLoxoneConfigInstances_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminate running Loxone Config instances ähnelt.
        /// </summary>
        internal static string TerminateAllLoxoneConfigInstances_Title {
            get {
                return ResourceManager.GetString("TerminateAllLoxoneConfigInstances_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use latest Version ähnelt.
        /// </summary>
        internal static string UseLatestVersion {
            get {
                return ResourceManager.GetString("UseLatestVersion", resourceCulture);
            }
        }

        internal static string UseLatestVersionHint {
            get {
                return ResourceManager.GetString("UseLatestVersionHint", resourceCulture);
            }
        }

        internal static string UpdateCheck_Checking {
            get {
                return ResourceManager.GetString("UpdateCheck_Checking", resourceCulture);
            }
        }

        internal static string UpdateCheck_Checking_WithDots {
            get {
                return ResourceManager.GetString("UpdateCheck_Checking_WithDots", resourceCulture);
            }
        }

        internal static string UpdateCheck_Downloading_WithDots {
            get {
                return ResourceManager.GetString("UpdateCheck_Downloading_WithDots", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpdateAvailable_Release {
            get {
                return ResourceManager.GetString("UpdateCheck_UpdateAvailable_Release", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpdateAvailable_Release_WithVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_UpdateAvailable_Release_WithVersion", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpdateAvailable_Beta {
            get {
                return ResourceManager.GetString("UpdateCheck_UpdateAvailable_Beta", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpdateAvailable_Beta_WithVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_UpdateAvailable_Beta_WithVersion", resourceCulture);
            }
        }
        
        internal static string UpdateCheck_UpdateAvailable_Alpha {
            get {
                return ResourceManager.GetString("UpdateCheck_UpdateAvailable_Alpha", resourceCulture);
            }
        }
        
        internal static string UpdateCheck_UpdateAvailable_Alpha_WithVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_UpdateAvailable_Alpha_WithVersion", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpToDate_Release {
            get {
                return ResourceManager.GetString("UpdateCheck_UpToDate_Release", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpToDate_Release_WithVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_UpToDate_Release_WithVersion", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpToDate_Beta {
            get {
                return ResourceManager.GetString("UpdateCheck_UpToDate_Beta", resourceCulture);
            }
        }

        internal static string UpdateCheck_UpToDate_Beta_WithVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_UpToDate_Beta_WithVersion", resourceCulture);
            }
        }
        
        internal static string UpdateCheck_UpToDate_Alpha {
            get {
                return ResourceManager.GetString("UpdateCheck_UpToDate_Alpha", resourceCulture);
            }
        }
        
        internal static string UpdateCheck_UpToDate_Alpha_WithVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_UpToDate_Alpha_WithVersion", resourceCulture);
            }
        }
        
        internal static string UpdateCheck_NoAlphaAvailable {
            get {
                return ResourceManager.GetString("UpdateCheck_NoAlphaAvailable", resourceCulture);
            }
        }

        internal static string UpdateCheck_Failed {
            get {
                return ResourceManager.GetString("UpdateCheck_Failed", resourceCulture);
            }
        }

        internal static string UpdateCheck_CheckAgain {
            get {
                return ResourceManager.GetString("UpdateCheck_CheckAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VersionSelector ähnelt.
        /// </summary>
        internal static string VersionSelectorTitle {
            get {
                return ResourceManager.GetString("VersionSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Autostartup ähnelt.
        /// </summary>
        internal static string WindowsAutostartup {
            get {
                return ResourceManager.GetString("WindowsAutostartup", resourceCulture);
            }
        }
    }
}
